# Generated by Django 4.2.28 on 2026-03-23 10:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المحل / العميل')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم صاحب المحل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف إضافي')),
                ('address', models.TextField(verbose_name='العنوان المكتوب')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط الطول')),
                ('customer_type', models.CharField(choices=[('RETAIL', 'قطاعي'), ('WHOLESALE', 'جملة'), ('SUPERMARKET', 'سوبر ماركت')], default='RETAIL', max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='حد الائتمان (مبلغ)')),
                ('credit_days_limit', models.PositiveIntegerField(default=30, verbose_name='حد الائتمان (بالأيام)')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المديونية الحالية')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي التحصيلات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم إضافي')),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('partial', 'جزئي')], default='cash', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='logistics.customer')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'verbose_name_plural': 'فواتير البيع',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='كود الصنف (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='باركود')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('base_unit', models.CharField(default='قطعة', max_length=20, verbose_name='الوحدة الصغرى (أصغر شيء)')),
                ('sub_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='الوحدة المتوسطة (مثلاً دستة)')),
                ('main_unit', models.CharField(default='كرتونة', max_length=20, verbose_name='الوحدة الكبرى')),
                ('conversion_factor_sub', models.PositiveIntegerField(default=1, verbose_name='كم قطعة في الوحدة المتوسطة؟')),
                ('conversion_factor_main', models.PositiveIntegerField(default=1, verbose_name='كم قطعة في الكرتونة؟')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='الوزن الإجمالي للكرتونة (كجم)')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='طول الكرتونة (سم)')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عرض الكرتونة (سم)')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ارتفاع الكرتونة (سم)')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='المقاس (مثلاً L, XL أو 42)')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='اللون')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر تكلفة الكرتونة')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر بيع الكرتونة (جمهور)')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للبيع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(editable=False, max_length=100, unique=True, verbose_name='رقم الفاتورة الداخلي')),
                ('supplier_invoice_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم فاتورة المورد (اختياري)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الفاتورة')),
            ],
            options={
                'verbose_name': 'فاتورة شراء',
                'verbose_name_plural': 'فواتير الشراء',
            },
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales_supervisor', 'مشرف'), ('sales_manager', 'مدير')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('geographic_area', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('rep_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('targets', models.JSONField(blank=True, default=dict)),
                ('insurance_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reps', to='logistics.salesmanager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم المرتجع')),
                ('date_returned', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المرتجع')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب المرتجع')),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي قيمة المرتجع')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='logistics.invoice', verbose_name='الفاتورة الأصلية')),
            ],
            options={
                'verbose_name': 'مرتجع مبيعات',
                'verbose_name_plural': 'مرتجعات المبيعات',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True, verbose_name='رقم الإذن')),
                ('status', models.CharField(choices=[('DRAFT', 'طلب تحميل (بإنتظار الموافقة)'), ('APPROVED', 'تمت الموافقة (قيد التحضير)'), ('IN_TRANSIT', 'في الطريق (في عهدة الناقل)'), ('COMPLETED', 'تم تأكيد العهدة (استلام كامل)'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إذن تحويل عهدة',
                'verbose_name_plural': 'أذون تحويل العهد',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد المورد (له)')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
            },
        ),
        migrations.CreateModel(
            name='WorkDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to='logistics.salesrepresentative')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المخزن/السيارة')),
                ('warehouse_type', models.CharField(choices=[('MAIN', 'المخزن الرئيسي'), ('VAN', 'مخزن سيارة المندوب')], default='MAIN', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_rep', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_warehouse', to='logistics.salesrepresentative', verbose_name='المندوب المسؤول')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_unit', models.CharField(choices=[('main', 'كرتونة'), ('sub', 'دستة/ربطة'), ('base', 'قطعة')], default='main', max_length=10, verbose_name='الوحدة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('is_received', models.BooleanField(default=False, verbose_name='تم تأكيد استلام الصنف')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='الصنف')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإيصال / مرجع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'سداد مورد',
                'verbose_name_plural': 'سدادات الموردين',
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='receiver_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='logistics.warehouse', verbose_name='إلى مخزن (المندوب)'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.salesrepresentative', verbose_name='المندوب صاحب الطلب'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='sender_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='logistics.warehouse', verbose_name='من مخزن (المصدر)'),
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_unit', models.CharField(choices=[('main', 'وحدة كبرى (كرتونة)'), ('sub', 'وحدة متوسطة (دستة/ربطة)'), ('base', 'وحدة صغرى (قطعة)')], default='base', max_length=10, verbose_name='الوحدة المرجعة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر الوحدة عند المرتجع')),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.product', verbose_name='الصنف المرتجع')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.salesreturn')),
            ],
            options={
                'verbose_name': 'صنف مرتجع',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_unit', models.CharField(choices=[('main', 'وحدة كبرى (كرتونة)'), ('sub', 'وحدة متوسطة (دستة/ربطة)'), ('base', 'وحدة صغرى (قطعة)')], default='main', max_length=10, verbose_name='وحدة الشراء')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر شراء الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.product', verbose_name='الصنف')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.warehouse', verbose_name='المخزن المستلم'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_unit', models.CharField(choices=[('main', 'وحدة كبرى (كرتونة)'), ('sub', 'وحدة متوسطة (دستة/ربطة)'), ('base', 'وحدة صغرى (قطعة)')], default='base', max_length=10, verbose_name='الوحدة المباعة')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('discount_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم/وحدة')),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صنف فاتورة',
                'verbose_name_plural': 'أصناف الفواتير',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.warehouse', verbose_name='المخزن (السحب من)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_customers', to='logistics.salesrepresentative', verbose_name='المندوب المسؤول'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المحصل')),
                ('collection_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحصيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المحصل / المندوب')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='logistics.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.invoice', verbose_name='الفاتورة (اختياري)')),
            ],
            options={
                'verbose_name': 'عملية تحصيل',
                'verbose_name_plural': 'التحصيلات',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='logistics.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='logistics.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'صنف بالمخزن',
                'verbose_name_plural': 'جرد المخازن',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
