# Generated by Django 4.2.28 on 2026-03-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=255, verbose_name='معرف المالك')),
                ('supermarket_name', models.CharField(max_length=255, verbose_name='اسم المتجر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_visible_in_store', models.BooleanField(default=True, verbose_name='مرئي للعملاء')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('store_type', models.CharField(choices=[('supermarket', 'سوبر ماركت'), ('restaurant', 'مطعم / كافيه'), ('pharmacy', 'صيدلية'), ('vegetables', 'خضروات وفاكهة')], default='supermarket', max_length=50)),
                ('trial_expiry_date', models.DateTimeField(verbose_name='تاريخ انتهاء الفترة التجريبية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'متجر',
                'verbose_name_plural': 'المتاجر',
            },
        ),
    ]
