# Generated by Django 4.2.28 on 2026-03-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صنف بالمخزن',
                'verbose_name_plural': 'جرد المخازن',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='كود الصنف (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='باركود')),
                ('unit', models.CharField(choices=[('PCS', 'قطعة'), ('BOX', 'كرتونة'), ('KG', 'كيلو')], default='PCS', max_length=10, verbose_name='وحدة القياس')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التكلفة')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع للجمهور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للبيع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sales_supervisor', 'مشرف'), ('sales_manager', 'مدير')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('geographic_area', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('rep_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('targets', models.JSONField(blank=True, default=dict)),
                ('insurance_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reps', to='logistics.salesmanager')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(max_length=50, unique=True, verbose_name='رقم الإذن')),
                ('status', models.CharField(choices=[('DRAFT', 'طلب تحميل (بإنتظار الموافقة)'), ('APPROVED', 'تمت الموافقة (قيد التحضير)'), ('IN_TRANSIT', 'في الطريق (في عهدة الناقل)'), ('COMPLETED', 'تم تأكيد العهدة (استلام كامل)'), ('CANCELLED', 'ملغي')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إذن تحويل عهدة',
                'verbose_name_plural': 'أذون تحويل العهد',
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_at_transfer', models.CharField(max_length=10, verbose_name='الوحدة وقت الطلب')),
                ('is_received', models.BooleanField(default=False, verbose_name='تم تأكيد استلام الصنف')),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='الصنف')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المخزن/السيارة')),
                ('warehouse_type', models.CharField(choices=[('MAIN', 'المخزن الرئيسي'), ('VAN', 'مخزن سيارة المندوب')], default='MAIN', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_rep', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_warehouse', to='logistics.salesrepresentative', verbose_name='المندوب المسؤول')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
            },
        ),
        migrations.CreateModel(
            name='WorkDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_logs', to='logistics.salesrepresentative')),
            ],
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='receiver_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='logistics.warehouse', verbose_name='إلى مخزن (المندوب)'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.salesrepresentative', verbose_name='المندوب صاحب الطلب'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='sender_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='logistics.warehouse', verbose_name='من مخزن (المصدر)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='logistics.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='logistics.warehouse', verbose_name='المخزن'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('warehouse', 'product')},
        ),
    ]
