# Generated by Django 4.2.28 on 2026-03-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTreasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='الخزينة المركزية', max_length=100)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'الخزينة الرئيسية',
                'verbose_name_plural': 'الخزينة الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='RepresentativeVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='العهدة النقدية الحالية (في يده)')),
                ('last_clearance_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تصفية حساب')),
                ('representative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to=settings.AUTH_USER_MODEL, verbose_name='المندوب')),
            ],
            options={
                'verbose_name': 'محفظة مندوب',
                'verbose_name_plural': 'محافظ المناديب (العهدة النقدية)',
            },
        ),
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('action_type', models.CharField(choices=[('INVOICE_CASH', 'مبيعات فاتورة كاش'), ('DEBT_COLLECTION', 'تحصيل مديونية'), ('CLEARANCE', 'تصفية عهدة (توريد للخزنة)')], max_length=20)),
                ('status', models.CharField(choices=[('HOLD', 'في عهدة المندوب'), ('SETTLED', 'تم التوريد للمركز الرئيسي'), ('CANCELLED', 'ملغى')], default='HOLD', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوريد الفعلي')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='القائم بالحركة')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.invoice', verbose_name='الفاتورة')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='logistics.representativevault')),
            ],
            options={
                'verbose_name': 'حركة تحصيل/توريد',
                'verbose_name_plural': 'سجل حركات النقدية',
            },
        ),
    ]
