# Generated by Django 4.2.28 on 2026-03-23 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import logistics.models.expenses


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_companytreasury_representativevault_collectionaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع المصروف')),
            ],
            options={
                'verbose_name': 'تصنيف مصاريف',
                'verbose_name_plural': 'تصنيفات المصاريف',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الصرف')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to=logistics.models.expenses.expense_upload_path, verbose_name='صورة المستند / الإيصال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات / بيان')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.expensecategory', verbose_name='نوع المصروف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الصرف')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصاريف',
            },
        ),
    ]
