# Generated by Django 4.2.28 on 2026-03-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_inventoryitem_product_salesmanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المحل / العميل')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم صاحب المحل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('alt_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف إضافي')),
                ('address', models.TextField(verbose_name='العنوان المكتوب')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط الطول')),
                ('customer_type', models.CharField(choices=[('RETAIL', 'قطاعي'), ('WHOLESALE', 'جملة'), ('SUPERMARKET', 'سوبر ماركت')], default='RETAIL', max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='حد الائتمان')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_customers', to='logistics.salesrepresentative', verbose_name='المندوب المسؤول')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
    ]
