# Generated by Django 4.2.28 on 2026-03-22 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('total_before_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('partial', 'جزئي')], default='cash', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_synced_to_platform', models.BooleanField(default=False)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='logistics.customer')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('discount_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='إجمالي السطر')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صنف فاتورة',
                'verbose_name_plural': 'أصناف الفواتير',
            },
        ),
    ]
