# Generated by Django 4.2.28 on 2026-03-22 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0004_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'صنف فاتورة'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='is_synced_to_platform',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم إضافي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم/قطعة'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر'),
        ),
    ]
