# Generated by Django 4.2.28 on 2026-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_days_limit',
            field=models.PositiveIntegerField(default=30, verbose_name='حد الائتمان (بالأيام)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي التحصيلات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='حد الائتمان (مبلغ)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='المديونية الحالية'),
        ),
    ]
