# Generated by Django 4.2.28 on 2026-03-22 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0006_customer_credit_days_limit_customer_total_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المحصل')),
                ('collection_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التحصيل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المحصل / المندوب')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='logistics.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.invoice', verbose_name='الفاتورة (اختياري)')),
            ],
            options={
                'verbose_name': 'عملية تحصيل',
                'verbose_name_plural': 'التحصيلات',
            },
        ),
    ]
