# Generated by Django 4.2.28 on 2026-03-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(default='قطعة', max_length=20, verbose_name='الوحدة الصغرى (أصغر شيء)'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='product',
            name='conversion_factor_main',
            field=models.PositiveIntegerField(default=1, verbose_name='كم قطعة في الكرتونة؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='conversion_factor_sub',
            field=models.PositiveIntegerField(default=1, verbose_name='كم قطعة في الوحدة المتوسطة؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ارتفاع الكرتونة (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='طول الكرتونة (سم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_unit',
            field=models.CharField(default='كرتونة', max_length=20, verbose_name='الوحدة الكبرى'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='المقاس (مثلاً L, XL أو 42)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الوحدة المتوسطة (اختياري - مثلاً دستة)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='الوزن الإجمالي للكرتونة (كجم)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='عرض الكرتونة (سم)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التكلفة (للقطعة)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر بيع الجمهور (للقطعة)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.category', verbose_name='القسم'),
        ),
    ]
