# Generated by Django 4.2.28 on 2026-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_category_remove_product_unit_product_base_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر تكلفة الكرتونة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر بيع الكرتونة (جمهور)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الوحدة المتوسطة (مثلاً دستة)'),
        ),
    ]
