# Generated by Django 4.2.28 on 2026-03-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_product_base_price_alter_product_selling_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True, verbose_name='رقم فاتورة المورد')),
                ('date', models.DateField(verbose_name='تاريخ الاستلام')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الفاتورة')),
            ],
            options={
                'verbose_name': 'فاتورة شراء',
                'verbose_name_plural': 'فواتير الشراء',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد (له)')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_main_unit', models.PositiveIntegerField(verbose_name='الكمية (بالكرتونة)')),
                ('cost_price_per_main_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر شراء الكرتونة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.product', verbose_name='الصنف')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.warehouse', verbose_name='المخزن المستلم'),
        ),
    ]
