# Generated by Django 4.2.28 on 2026-03-23 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_purchaseinvoice_supplier_purchaseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_invoice_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم فاتورة المورد (اختياري)'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_no',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='رقم الفاتورة الداخلي'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد المورد (له)'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإيصال / مرجع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='logistics.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'سداد مورد',
                'verbose_name_plural': 'سدادات الموردين',
            },
        ),
    ]
