# Generated by Django 4.2.28 on 2026-03-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_purchaseinvoice_supplier_invoice_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_created'], 'verbose_name': 'فاتورة بيع', 'verbose_name_plural': 'فواتير البيع'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'صنف فاتورة', 'verbose_name_plural': 'أصناف الفواتير'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.warehouse', verbose_name='المخزن (السحب من)'),
        ),
    ]
