# Generated by Django 4.2.28 on 2026-03-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم المرتجع')),
                ('date_returned', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المرتجع')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب المرتجع')),
                ('total_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي قيمة المرتجع')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='logistics.invoice', verbose_name='الفاتورة الأصلية')),
            ],
            options={
                'verbose_name': 'مرتجع مبيعات',
                'verbose_name_plural': 'مرتجعات المبيعات',
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المرتجعة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة عند المرتجع')),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.product', verbose_name='الصنف المرتجع')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.salesreturn')),
            ],
            options={
                'verbose_name': 'صنف مرتجع',
            },
        ),
    ]
